# Generated by Django 5.2.14 on 2026-09-11 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("nid", models.CharField(max_length=20, unique=True)),
                ("shop_name", models.CharField(max_length=150)),
                ("district", models.CharField(max_length=50)),
                ("thana", models.CharField(max_length=50)),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "commission_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Wakalah fee percentage for agent services",
                        max_digits=5,
                    ),
                ),
                (
                    "daily_limit",
                    models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "ordering": ["shop_name"],
                "indexes": [
                    models.Index(
                        fields=["district", "status"], name="agents_agen_distric_3620b5_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fee", models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ("commission", models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("cash_in", "Cash In"), ("cash_out", "Cash Out")], max_length=8
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("otp", models.CharField(blank=True, max_length=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="agents.agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Transaction",
                "verbose_name_plural": "Agent Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agent", "-created_at"], name="agents_agen_agent_i_89ac79_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"], name="agents_agen_user_id_bf6ec7_idx"
                    ),
                ],
            },
        ),
    ]
