# Generated by Django 5.2.14 on 2026-09-11 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=10, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ticket Category",
                "verbose_name_plural": "Ticket Categories",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="TicketProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("logo", models.FileField(blank=True, upload_to="tickets/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="providers",
                        to="tickets.ticketcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Provider",
                "verbose_name_plural": "Ticket Providers",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TicketTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Bus name, train number, movie title, flight number, event name",
                        max_length=150,
                    ),
                ),
                ("origin", models.CharField(blank=True, max_length=100)),
                ("destination", models.CharField(blank=True, max_length=100)),
                (
                    "departure_time",
                    models.CharField(blank=True, help_text="e.g. 08:00 AM", max_length=10),
                ),
                ("arrival_time", models.CharField(blank=True, max_length=10)),
                ("coach_class", models.CharField(blank=True, max_length=50)),
                (
                    "coaches",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Coach designations for trains, e.g. ["ক", "খ", "গ"]',
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="tickets.ticketprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Trip",
                "verbose_name_plural": "Ticket Trips",
                "ordering": ["provider", "name"],
            },
        ),
        migrations.CreateModel(
            name="TicketBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("booking_reference", models.CharField(editable=False, max_length=30, unique=True)),
                ("journey_date", models.DateField()),
                (
                    "departure_time",
                    models.CharField(blank=True, help_text="e.g. 08:30 AM", max_length=10),
                ),
                (
                    "origin",
                    models.CharField(blank=True, help_text="Origin city/station", max_length=100),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True, help_text="Destination city/station", max_length=100
                    ),
                ),
                (
                    "trip_name",
                    models.CharField(
                        blank=True,
                        help_text="Bus name, train number, flight number, movie name, event name",
                        max_length=150,
                    ),
                ),
                (
                    "coach_class",
                    models.CharField(
                        blank=True,
                        help_text="AC/Non-AC, Shovon/First Class, Economy/Business, Regular/Premium",
                        max_length=50,
                    ),
                ),
                (
                    "coach",
                    models.CharField(
                        blank=True, help_text="Coach/bogi number or name", max_length=20
                    ),
                ),
                (
                    "seat_number",
                    models.CharField(blank=True, help_text="e.g. A1, B3-B5", max_length=50),
                ),
                ("passengers", models.PositiveSmallIntegerField(default=1)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fee", models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="tickets.ticketprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Booking",
                "verbose_name_plural": "Ticket Bookings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="tickets_tic_user_id_066c64_idx"
                    )
                ],
            },
        ),
    ]
