# Generated by Django 5.2.14 on 2026-09-11 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("opening_balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("closing_balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_credits", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_debits", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction_count", models.PositiveIntegerField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Statement",
                "verbose_name_plural": "Account Statements",
                "ordering": ["-year", "-month"],
                "unique_together": {("user", "year", "month")},
            },
        ),
    ]
