# Generated by Django 5.2.14 on 2026-09-11 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("operator_code", models.CharField(max_length=10, unique=True)),
                ("logo", models.FileField(blank=True, upload_to="logos/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Operator",
                "verbose_name_plural": "Operators",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OperatorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=10, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Operator Type",
                "verbose_name_plural": "Operator Types",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="DataPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("volume", models.CharField(max_length=50)),
                ("validity_days", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_packs",
                        to="recharge.operator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Pack",
                "verbose_name_plural": "Data Packs",
                "ordering": ["amount"],
            },
        ),
        migrations.AddField(
            model_name="operator",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operators",
                to="recharge.operatortype",
            ),
        ),
        migrations.CreateModel(
            name="RechargeTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("fee", models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                (
                    "recharge_type",
                    models.CharField(
                        choices=[
                            ("prepaid", "Prepaid Recharge"),
                            ("postpaid", "Postpaid Bill"),
                            ("data_pack", "Data Pack"),
                        ],
                        default="prepaid",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_pack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recharges",
                        to="recharge.datapack",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recharges",
                        to="recharge.operator",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recharge_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recharge Transaction",
                "verbose_name_plural": "Recharge Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="recharge_re_user_id_398224_idx"
                    )
                ],
            },
        ),
    ]
