# Generated by Django 5.2.14 on 2026-09-11 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RemittancePartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=50)),
                ("currency", models.CharField(help_text="ISO 4217 currency code", max_length=3)),
                ("exchange_rate", models.DecimalField(decimal_places=2, max_digits=8)),
                ("logo", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Remittance Partner",
                "verbose_name_plural": "Remittance Partners",
                "ordering": ["country", "name"],
            },
        ),
        migrations.CreateModel(
            name="RemittanceTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sender_name", models.CharField(max_length=100)),
                ("sender_country", models.CharField(max_length=50)),
                ("amount_foreign", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_bdt", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Spot exchange rate per Sarraf/Hawala principles",
                        max_digits=8,
                    ),
                ),
                ("reference_number", models.CharField(editable=False, max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remittances",
                        to="remittance.remittancepartner",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remittance_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Remittance Transaction",
                "verbose_name_plural": "Remittance Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="remittance__user_id_f4de5f_idx"
                    )
                ],
            },
        ),
    ]
