# Generated by Django 5.2.14 on 2026-09-11 09:14

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HawlTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nisab_crossed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user's wealth first crossed the nisab threshold",
                        null=True,
                    ),
                ),
                (
                    "next_hawl_date",
                    models.DateField(
                        blank=True,
                        help_text="One lunar year after nisab_crossed_at; zakat becomes due",
                        null=True,
                    ),
                ),
                (
                    "is_eligible",
                    models.BooleanField(
                        default=False, help_text="Whether the user currently has wealth above nisab"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hawl_tracking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hawl Tracking",
                "verbose_name_plural": "Hawl Tracking",
            },
        ),
        migrations.CreateModel(
            name="Sadaqah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("given_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cause",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional cause this sadaqah supports",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sadaqah_donations",
                        to="accounts.charitycause",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foundation receiving this sadaqah",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_sadaqah",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sadaqah_donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sadaqah",
                "verbose_name_plural": "Sadaqah",
                "ordering": ["-given_at"],
            },
        ),
        migrations.CreateModel(
            name="SadaqahJariyah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("monthly", "Monthly")], default="monthly", max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(default=django.utils.timezone.localdate)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                (
                    "total_donated",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cause",
                    models.ForeignKey(
                        blank=True,
                        help_text="Recurring cause (e.g., water well, education fund)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sadaqah_jariyah_donations",
                        to="accounts.charitycause",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foundation receiving this sadaqah jariyah",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_sadaqah_jariyah",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sadaqah_jariyah_donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sadaqah Jariyah",
                "verbose_name_plural": "Sadaqah Jariyah",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ZakatPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "asset_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., cash, gold, silver, business",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hawl_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="The lunar year this zakat covers", null=True
                    ),
                ),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foundation receiving this zakat",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_zakat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zakat_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zakat Payment",
                "verbose_name_plural": "Zakat Payments",
                "ordering": ["-paid_at"],
            },
        ),
    ]
