# Generated by Django 5.2.14 on 2026-09-11 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=15, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Biller Category",
                "verbose_name_plural": "Biller Categories",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Biller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("biller_code", models.CharField(max_length=20, unique=True)),
                ("logo", models.FileField(blank=True, upload_to="billers/")),
                ("account_no_label", models.CharField(default="Account Number", max_length=50)),
                ("amount_no_label", models.CharField(default="Bill Number", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billers",
                        to="billpay.billercategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biller",
                "verbose_name_plural": "Billers",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="BillPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("account_number", models.CharField(max_length=50)),
                ("bill_number", models.CharField(blank=True, max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fee", models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ("bill_month", models.CharField(blank=True, max_length=10)),
                ("reference", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "biller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billpay.biller",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill Payment",
                "verbose_name_plural": "Bill Payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="billpay_bil_user_id_9251c6_idx"
                    ),
                    models.Index(
                        fields=["biller", "-created_at"], name="billpay_bil_biller__03cf03_idx"
                    ),
                ],
            },
        ),
    ]
