# Generated by Django 5.2.14 on 2026-09-11 09:14

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MudarabahPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("duration_months", models.PositiveIntegerField()),
                ("monthly_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "profit_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Mudarabah profit-sharing ratio (e.g., 50.00 = 50%)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mudarabah Plan",
                "verbose_name_plural": "Mudarabah Plans",
                "ordering": ["duration_months", "monthly_amount"],
            },
        ),
        migrations.CreateModel(
            name="MudarabahAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("account_number", models.CharField(editable=False, max_length=12, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("matured", "Matured"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.localdate)),
                ("maturity_date", models.DateField()),
                (
                    "total_deposited",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "expected_payout",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mudarabah_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="savings.mudarabahplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mudarabah Account",
                "verbose_name_plural": "Mudarabah Accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MudarabahContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("installment_number", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("missed", "Missed")],
                        default="paid",
                        max_length=10,
                    ),
                ),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mudarabah_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="savings.mudarabahaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mudarabah Contribution",
                "verbose_name_plural": "Mudarabah Contributions",
                "ordering": ["installment_number"],
                "unique_together": {("mudarabah_account", "installment_number")},
            },
        ),
    ]
