# Generated by Django 5.2.14 on 2026-09-11 09:14

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QardHasanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tenure_days", models.PositiveIntegerField(help_text="Repayment period in days")),
                (
                    "service_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Flat service fee (not percentage-based riba)",
                        max_digits=8,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Qard Hasan Product",
                "verbose_name_plural": "Qard Hasan Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QardHasanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("loan_reference", models.CharField(editable=False, max_length=20, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "service_fee",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "hibah_given",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Voluntary gift from borrower on top of principal",
                        max_digits=8,
                    ),
                ),
                ("tenure_days", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("disbursed", "Disbursed"),
                            ("repaid", "Repaid"),
                            ("rejected", "Rejected"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qard_hasan_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="loans.qardhasanproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qard Hasan Application",
                "verbose_name_plural": "Qard Hasan Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QardHasanRepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "hibah",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Voluntary extra payment as gift",
                        max_digits=8,
                    ),
                ),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="loans.qardhasanapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qard Hasan Repayment",
                "verbose_name_plural": "Qard Hasan Repayments",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.AddIndex(
            model_name="qardhasanapplication",
            index=models.Index(
                fields=["user", "-created_at"], name="loans_qardh_user_id_07a572_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qardhasanapplication",
            index=models.Index(fields=["status"], name="loans_qardh_status_449084_idx"),
        ),
    ]
