# Generated by Django 5.2.14 on 2026-09-11 09:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_money_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_money_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Money Request",
                "verbose_name_plural": "Money Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["requester", "-created_at"], name="transaction_request_6664cd_idx"
                    ),
                    models.Index(
                        fields=["target", "-created_at"], name="transaction_target__d07f4b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reference_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("counterparty", models.CharField(blank=True, default="", max_length=150)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fee", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("send", "Send Money"),
                            ("cash_in", "Cash In"),
                            ("cash_out", "Cash Out"),
                            ("payment", "QR Payment"),
                            ("bill", "Bill Payment"),
                            ("recharge", "Mobile Recharge"),
                            ("bank", "Bank Transfer"),
                            ("savings", "Savings"),
                            ("charity", "Charity"),
                            ("loan", "Qard Hasan"),
                            ("ticket", "Ticket Booking"),
                            ("remittance", "Remittance"),
                            ("gateway", "Gateway Payment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_payments",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "-created_at"], name="transaction_sender__ce1ef1_idx"
                    ),
                    models.Index(
                        fields=["receiver", "-created_at"], name="transaction_receive_d402ad_idx"
                    ),
                    models.Index(
                        fields=["merchant", "-created_at"], name="transaction_merchan_907052_idx"
                    ),
                ],
            },
        ),
    ]
